"""Carousel card covers: 16:10 (build_cover), designed on 800x500 for ~360px display. Min text 26 design px (>=11.7px on screen)."""
import ds5 as L, hubs5 as H
from qa import width as tw
def cv(b,title,desc):
    L.W,L.H=800,500
    s=L.canvas(b,title=title,desc=desc)
    L.W,L.H=1200,800
    return s
T,rect,chip,button,avatar,icon=L.T,L.rect,L.chip,L.button,L.avatar,L.icon
def big_button(x,y,w,h,label,ic=None,primary=True):
    b=rect(x,y,w,h,16,"url(#gAcc)" if primary else "#fff",None if primary else L.LINE,2)
    tw_=tw(label,28,700); ox=x+w/2-(tw_+(38 if ic else 0))/2; fg="#fff" if primary else L.INK
    if ic: b+=icon(ic,ox,y+h/2-14,28,fg,2.4)
    return b+T(ox+(38 if ic else 0),y+h/2+10,label,28,700,fg)
def aab():
    H.set_hub("aab"); b=H.spot(150,80,500,340)+rect(150,80,500,340,28,"#fff",L.LINE,1.5,"e2")
    b+=icon("hash",186,118,30,L.SUB,2.4)+T(226,144,"approvals",30,700,L.INK)+H.hair(150,176,650)
    b+=rect(186,204,64,64,16,"url(#gAcc)")+icon("sparkles",202,220,32,"#fff",2)
    b+=T(272,232,"$4,800 request",32,700,L.INK,tnum=True)+T(272,268,"Design licenses",26,500,L.MUTED)
    b+=big_button(186,312,232,72,"Approve","check")+big_button(434,312,180,72,"Decline",None,False)
    b+=H.click(396,368)
    return cv(b,"Approval workflow","An approval request in Slack with Approve and Decline buttons, generated by Emergent.")
def lp():
    H.set_hub("lp"); X,Y,W_=130,60,540
    b=H.spot(X,Y,W_,380)+rect(X,Y,W_,380,28,"#fff",L.LINE,1.5,"e2")+f'<path d="M{X} {Y+56} V{Y+28} a28 28 0 0 1 28 -28 H{X+W_-28} a28 28 0 0 1 28 28 V{Y+56} Z" fill="#FBFBFD"/>'+H.hair(X,Y+56,X+W_)
    for i in range(3): b+=f'<circle cx="{X+30+i*22}" cy="{Y+28}" r="7" fill="#E3E6EE"/>'
    cx=X+W_/2
    b+=f'<circle cx="{cx}" cy="{Y+136}" r="44" fill="{L.OK_S}"/>'+icon("check",cx-24,Y+112,48,L.OK,2.6)
    b+=T(cx,Y+236,"You're in.",40,800,L.INK,"middle",-0.8)
    b+=big_button(cx-170,Y+270,340,72,"Download","download")+H.click(cx+150,Y+330)
    return cv(b,"Thank you page","A thank you page confirming a signup with a download button, generated by Emergent.")
def form():
    H.set_hub("form"); X,Y,W_=140,70,520
    b=H.spot(X,Y,W_,360)+rect(X,Y,W_,360,28,"#fff",L.LINE,1.5,"e2")
    b+=f'<circle cx="{X+62}" cy="{Y+70}" r="34" fill="{L.OK_S}"/>'+icon("check",X+43,Y+51,38,L.OK,2.6)+T(X+116,Y+84,"Approved",40,800,L.INK,ls=-0.8)
    b+=rect(X+32,Y+140,W_-64,140,20,L.ACC_S,L.ACC,2.5)+T(X+62,Y+186,"Referral code",26,700,L.ACC_D)+T(X+62,Y+250,"MAYA15",52,800,L.INK,ls=6)
    b+=T(X+32,Y+326,"Fit score 92",26,600,L.SUB,tnum=True)
    return cv(b,"Creator application","An approved creator application with a referral code, generated by Emergent.")
def sqb():
    H.set_hub("sqb"); X,Y,W_=130,60,540
    b=H.spot(X,Y,W_,380)+rect(X,Y,W_,380,28,"#fff",L.LINE,1.5,"e2")
    b+=T(X+36,Y+76,"How did we do?",36,800,L.INK,ls=-0.6)
    b+=H.stars(X+36,Y+140,5,54,14)
    b+=H.hair(X+36,Y+196,X+W_-36)
    b+=T(X+36,Y+262,"CSAT",28,700,L.MUTED)+T(X+36,Y+330,"4.6",60,800,L.INK,ls=-1.5,tnum=True)
    lab="+0.4 this month"; cw=int(tw(lab,26,600)+56); b+=chip(X+W_-36-cw,Y+282,lab,"ok",cw,52,26)
    return cv(b,"Customer satisfaction survey","A satisfaction survey with a five-star rating and a CSAT score, generated by Emergent.")
COVERS={"aab":aab,"lp":lp,"form":form,"sqb":sqb}
