"""retro.py: the learning loop after a batch (LESSONS.md section 3).  hubctl retro BATCH  -> status/metrics.md + a LESSONS section 5 line.
Metrics from the ship ledger (status/ship/BATCH.json), token use (status/usage.jsonl), the PAA gate and QC as they stand now."""
import datetime, glob, json, os, statistics, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
for d in ("ops", "qc", "pipeline"): sys.path.insert(0, os.path.join(ROOT, d))

def ts(s): return datetime.datetime.strptime(s, "%Y-%m-%d %H:%M UTC")

def main(args):
    name = args[0]; L = json.load(open(os.path.join(ROOT, "status", "ship", name + ".json")))
    import ship as S, paa_gate as PG
    P = L["pages"]; urls = list(P); shipped = [u for u in urls if P[u]["stage"] == "done" and not P[u].get("stopped")]; held = [u for u in urls if P[u].get("stopped")]
    first_qc = [u for u in urls if next((h["ok"] for h in P[u]["history"] if h["stage"] == "check"), None) is True]
    reviewed = [u for u in urls if any(h["stage"] == "review" and h["ok"] for h in P[u]["history"])]
    reworked = [u for u in urls if any(h["stage"] == "rework" for h in P[u]["history"])]
    gate10 = qc0 = 0
    for u in shipped:
        its, page = PG.run_spec(PG.Gate(u)); gate10 += sum(i["verdict"] != "reject" for i in its) == 10 and not page
        qc0 += S.qc_total(u) == 0
    tok = {}
    for l in open(os.path.join(ROOT, "status", "usage.jsonl")):
        r = json.loads(l)
        if r["url"] in P and r.get("agent", "").startswith("launch"): tok.setdefault(r["role"], {}).setdefault(r["url"], 0); tok[r["role"]][r["url"]] += r["tokens"]
    wall = [(ts(P[u]["history"][-1]["t"]) - ts(P[u]["history"][0]["t"])).total_seconds() / 3600 for u in shipped if len(P[u]["history"]) > 1]
    pct = lambda a, b: f"{a}/{b} ({100 * a // max(b, 1)}%)"
    audit = sorted(glob.glob(os.path.join(ROOT, "audits", "live", "*", "findings.json")))
    au = json.load(open(audit[-1])) if audit else None
    L_ = [f"# Metrics: {name} (retro {datetime.date.today()})", "", "Generated by `hubctl retro` (ops/retro.py). LESSONS.md section 3 defines each metric.", "",
          "| Metric | Value |", "|---|---|",
          f"| Pages in the batch | {len(urls)} |", f"| Shipped (live) | {len(shipped)} |", f"| Held | {len(held)} |",
          f"| First-pass QC (writer pass reached QC 0) | {pct(len(first_qc), len(urls))} |",
          f"| Review blocking-finding rate (pages sent to rework) | {pct(len(reworked), len(reviewed))} |",
          f"| QC 0 now (shipped pages) | {pct(qc0, len(shipped))} |", f"| PAA gate 10/10 now (shipped pages) | {pct(gate10, len(shipped))} |",
          "| Human catches vs gate at PA13 | 5 human catches in 210 questions (2.4%); 3 of the 5 now guarded by PA14 |",
          "| Launch-day catches the gates missed (Divit) | brand / file-format FAQ questions on 12 of 20 pages (23 questions), long hero and how-to descriptions on 20 of 20 -> PA14, PA15, D1, D2 |",
          f"| Writer tokens per page (mean) | {statistics.mean(tok.get('writer', {}).values()):,.0f} over {len(tok.get('writer', {}))} pages |" if tok.get("writer") else "| Writer tokens per page | not logged |",
          f"| Review tokens per page (mean) | {statistics.mean(tok.get('reviewer', {}).values()):,.0f} over {len(tok.get('reviewer', {}))} pages |" if tok.get("reviewer") else "| Review tokens per page | not logged |",
          f"| Wall-clock per shipped page, first step to done (median) | {statistics.median(wall):.1f} h |" if wall else "| Wall-clock | n/a |",
          f"| Live audit (latest, {au['date']}) | {len(au['findings'])} findings |" if au else "| Live audit | not run |", "",
          "## Held and why", ""] + [f"- {u}: {P[u]['stopped'][:160]}" for u in held] + ["",
          "## What to change for batch 2 (one combined pass, LESSONS rule 2)", "",
          "- Apply PA14/PA15/D1/D2 and the FAQ moat lines (F9) in the writer pass, not after review.",
          "- Gate PA9 on normalised text (the PA13 near-duplicates); keep the 4 open golden cases as the acceptance test.",
          "- No production publish without the publish watch and a staging verify_launch pass (two unplanned publishes on launch day)."]
    open(os.path.join(ROOT, "status", "metrics.md"), "w").write("\n".join(L_) + "\n")
    line = (f"- {datetime.date.today()} · retro {name}: {len(shipped)} shipped, {len(held)} held; first-pass QC {pct(len(first_qc), len(urls))}; "
            f"review blocking {pct(len(reworked), len(reviewed))}; launch-day gate misses (brands, file formats, descriptions) on 20/20 pages · PA14, PA15, D1, D2, F9 and golden cases added (status/metrics.md)\n")
    p = os.path.join(ROOT, "LESSONS.md"); t = open(p).read(); o = "## 5. Incident log (newest first; one line each: date, what, check added)\n"
    if f"retro {name}:" not in t: open(p, "w").write(t.replace(o, o + line, 1))
    print("\n".join(L_[:20]))

if __name__ == "__main__":
    main(sys.argv[1:])
